# Generated by Django 6.0.7 on 2026-07-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='casual_leave_balance',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='user',
            name='earned_leave_balance',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='user',
            name='sick_leave_balance',
            field=models.IntegerField(default=12),
        ),
    ]
